### ISSUE TITLE
Will the code be released in the near future?

### ISSUE THREAD

**Issue by lnexenl** [carlinds/splatad#1]
Hi, I have read your paper today, really awesome!!! 

I can't wait to run your algorithm, and may I ask when the code will be released?

**Comment by carlinds** [comment]
Hi,
I'm glad you enjoyed the paper! Our ambition is to release the code as soon as the article has undergone peer reviews and been published.

**Comment by lnexenl** [comment]
Thank for your kindly response! I will be here waiting for your code.

**Comment by phb-shiyige-fw** [comment]
Your work is really excellent, I look forward to your open source code!

**Comment by hungdche** [comment]
Congrats on the CVPR acceptance! Look forward to the code release!
