### ISSUE TITLE
Hello,about the GPU VRAM requirement

### ISSUE THREAD

**Issue by zzz5y** [carlinds/splatad#2]
Thanks for you great work!And after reading the paper,I am a little confused hou much VRAM need for training in splatad!
Thank you!

**Comment by georghess** [comment]
Hi, any part in the paper in particular that was confusing? We can look into updating it in that case. 
Needed VRAM varies a bit depending on the size of the dataset and whether you cache the data on GPU (faster training) or on CPU (less VRAM required). I think on the low end (pandaset, cache data on CPU) ~4GB is enough. When training on nuScenes and caching on GPU, top VRAM for our runs is ~8-9GB.

**Comment by zzz5y** [comment]
> Hi, any part in the paper in particular that was confusing? We can look into updating it in that case. Needed VRAM varies a bit depending on the size of the dataset and whether you cache the data on GPU (faster training) or on CPU (less VRAM required). I think on the low end (pandaset, cache data on CPU) ~4GB is enough. When training on nuScenes and caching on GPU, top VRAM for our runs is ~8-9GB.

Thank you very much for your quick reply and excellent work, and I apologize for any unclear description on my issue. I have no confusion regarding the paper; I just had a simple question about the VRAM requirements for GPU training. Thank you very much for your response.I got the problem answer!
